namespace: '{{ .Release.Namespace }}'
namePrefix: '{{ include "conduit-operator.fullname" . }}-'

patchesStrategicMerge:
- manager_webhook_patch.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: '{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}'
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: '{{ .Values.image.pullPolicy }}'
    - op: add
      path: /spec/template/metadata/annotations/rollme
      value: '{{ randAlphaNum 5 | quote }}'
    - op: replace
      path: /spec/template/spec/serviceAccountName
      value: '{{ include "conduit-operator.serviceAccountName" . }}'
  target:
    kind: Deployment

resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

# configMapGenerator:
# - name: manager-config
#  files:
#  - controller_manager_config.yaml
