apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: controller 
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
