---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-operator-conduit-io-v1alpha-conduit
  failurePolicy: Fail
  name: mconduit-v1alpha.kb.io
  rules:
  - apiGroups:
    - operator.conduit.io
    apiVersions:
    - v1alpha
    operations:
    - CREATE
    - UPDATE
    resources:
    - conduits
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-operator-conduit-io-v1alpha-conduit
  failurePolicy: Fail
  name: vconduit-v1alpha.kb.io
  rules:
  - apiGroups:
    - operator.conduit.io
    apiVersions:
    - v1alpha
    operations:
    - CREATE
    - UPDATE
    resources:
    - conduits
  sideEffects: None
