# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: conduits.operator.conduit.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: system
          name: '{{ include "conduit-operator.fullname" . }}-webhook'
          path: /convert
      conversionReviewVersions:
      - v1
