apiVersion: v1
data:
  type: c3RydWN0dXJlZAo=
  options: aWQ6aW50LG5hbWU6c3RyaW5nLGNvbXBhbnk6c3RyaW5nLHRyaWFsOmJvb2wK
kind: Secret
metadata:
  name: conduit-generator-secrets-format
type: Opaque
---
apiVersion: operator.conduit.io/v1
kind: Conduit
metadata:
  name: conduit-generator-secrets
spec:
  running: true
  name: generator.standalone.log
  description: generator pipline
  connectors:
    - name: source-connector
      type: source
      plugin: conduitio/conduit-connector-generator
      pluginVersion: v0.5.0
      settings:
        - name: format.type
          secretRef:
            key: type
            name: conduit-generator-secrets-format
        - name: format.options
          secretRef:
            key: options
            name: conduit-generator-secrets-format
        - name: recordCount
          value: "3"
    - name: destination-connector
      type: destination
      plugin: conduitio/conduit-connector-log
      pluginVersion: v0.3.0
