apiVersion: operator.conduit.io/v1alpha
kind: Conduit
metadata:
  name: conduit-generator-image-ver
spec:
  running: false
  name: generator.log
  description: generator pipeline
  image: ghcr.io/conduitio/conduit
  version: v0.11.1
  connectors:
    - name: source-connector
      type: source
      plugin: "builtin:generator"
      pluginName: "builtin:generator"
      settings:
        - name: format.type
          value: structured
        - name: format.options.id
          value: "int"
        - name: format.options.name
          value: "string"
        - name: format.options.company
          value: "string"
        - name: format.options.trial
          value: "bool"
        - name: recordCount
          value: "3"
    - name: destination-connector
      type: destination
      plugin: "builtin:log"
      pluginName: "builtin:log"
