apiVersion: operator.conduit.io/v1alpha
kind: Conduit
metadata:
  name: conduit-generator
  namespace: default
spec:
  running: true
  name: generator.log
  description: generator pipeline
  connectors:
    - name: source-connector
      type: source
      plugin: builtin:generator
      settings:
        - name: format.type
          value: structured
        - name: format.options
          value: "id:int,name:string,company:string,trial:bool"
        - name: recordCount
          value: "3"
    - name: destination-connector
      type: destination
      plugin: builtin:log
