apiVersion: v1
data:
  type: c3RydWN0dXJlZAo=
  password-type: c3RyaW5n
kind: Secret
metadata:
  name: conduit-generator-secrets-format
type: Opaque
---
apiVersion: operator.conduit.io/v1alpha
kind: Conduit
metadata:
  name: conduit-generator-secrets
spec:
  running: true
  name: generator.standalone.log
  description: generator pipeline
  connectors:
    - name: source-connector
      type: source
      plugin: conduitio/conduit-connector-generator
      pluginVersion: v0.7.0
      settings:
        - name: format.type
          secretRef:
            key: type
            name: conduit-generator-secrets-format
        - name: format.options.id
          value: "int"
        - name: format.options.name
          value: "string"
        - name: format.options.company
          value: "string"
        - name: format.options.trial
          value: "bool"
        - name: format.options.password
          secretRef:
            key: password-type
            name: conduit-generator-secrets-format
        - name: recordCount
          value: "3"
    - name: destination-connector
      type: destination
      plugin: conduitio/conduit-connector-log
      pluginVersion: v0.4.0
