apiVersion: operator.conduit.io/v1alpha
kind: Conduit
metadata:
  name: conduit-sample
spec:
  running: true
  name: file-pipeline
  description: test pipeline
  connectors:
    - name: source-connector
      type: source
      plugin: foobar
      settings:
        - name: path
          secretRef:
            key: source_file
            name: conduit-sample
