apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: '{{ include "conduit-operator.fullname" . }}-serving-cert'
  namespace: '{{ .Release.Namespace }}'
spec:
  dnsNames:
  - '{{ include "conduit-operator.fullname" . }}-webhook.{{ .Release.Namespace }}.svc'
  - '{{ include "conduit-operator.fullname" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: '{{ include "conduit-operator.fullname" . }}-selfsigned-issuer'
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: '{{ include "conduit-operator.fullname" . }}-selfsigned-issuer'
  namespace: '{{ .Release.Namespace }}'
spec:
  selfSigned: {}
