apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "conduit-operator.fullname" . }}-instance-config'
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "conduit-operator.labels" . | nindent 4 }}
data:
  {{ .Values.controller.conduitInstance.metadataFile }}: |
    {{- with .Values.controller.conduitMetadata }}
      {{- toYaml . | nindent 8 }}
    {{- end }}
