apiVersion: v1
kind: Service
metadata:
  name: '{{ include "conduit-operator.fullname" . }}-webhook'
  namespace: '{{ .Release.Namespace }}'
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    {{- include "conduit-operator.selectorLabels" . | nindent 8 }}
