namespace: '{{ .Release.Namespace }}'
namePrefix: '{{ include "conduit-operator.fullname" . }}-'

resources:
- issuer.yaml
- certificate-webhook.yaml
- certificate-metrics.yaml

configurations:
- kustomizeconfig.yaml
