#!/bin/bash -eu

set -o pipefail

if [ 0 = $# ]; then
	echo "usage: $0 <chart-dir> <build-dir> [index to merge to]"
	exit 1
fi

repo_root=$(git rev-parse --show-toplevel)
chart_dir="$repo_root/$1"
dst_dir="$2"

args=(--debug)
if [[ -n "${3-}" ]]; then
  args+=(--merge "$3")
fi

pushd "$dst_dir"
helm package "$chart_dir"
helm repo index . "${args[@]}"
popd > /dev/null
