name: Helm Release
on:
  workflow_dispatch:
    ref: main
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build-push-helm-chart:
    name: Build and push Helm chart pkg
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: charts/build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: gh-pages
          path: ${{ env.BUILD_DIR }}
      - name: Package Helm Chart
        env:
          WORKSPACE_BUILD_DIR: ${{ github.WORKSPACE }}/${{ env.BUILD_DIR}}
        run: |
          mkdir -p ${WORKSPACE_BUILD_DIR}
          scripts/package-chart charts/conduit-operator ${WORKSPACE_BUILD_DIR} ${WORKSPACE_BUILD_DIR}/index.yaml
          ls -all ${WORKSPACE_BUILD_DIR}
          cat ${WORKSPACE_BUILD_DIR}/index.yaml
      - name: Release Helm Chart
        uses: peaceiris/actions-gh-pages@v4
        env:
          WORKSPACE_BUILD_DIR: ${{ github.WORKSPACE }}/${{ env.BUILD_DIR}}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.WORKSPACE_BUILD_DIR }}
          keep_files: true
